export const questions = [
  {
    id: 1,
    title: "Cuanto es 5 + 7",
    answer: "12",
    options: ["12", "13", "6", "7"],
  },
  {
    id: 2,
    title: "¿Cuál es el nombre del río más largo del mundo?",
    answer: "Río Nilo",
    options: ["Río Nilo", "Río Amazonas", "Río Congo", "Río Danubio"],
  },
  {
    id: 3,
    title: "¿Cuál es el oceano mas grande del mundo?",
    answer: "Oceano Pacífico",
    options: [
      "Oceano Atlántico",
      "Oceano Pacífico",
      "Oceano Indico",
      "Oceano Índico",
    ],
  },
  {
    id: 4,
    title: "¿Cuál es el país más grande del mundo?",
    answer: "Rusia",
    options: ["Rusia", "Estados Unidos", "China", "Corea del Norte"],
  },
  {
    id: 5,
    title: "¿Cuál es el país que tiene forma de bota?",
    answer: "Italia",
    options: ["Italia", "Francia", "Alemania", "Japón"],
  },
  {
    id: 6,
    title: "¿Cuál es el país mas poblado de la tierra?",
    answer: "China",
    options: ["China", "Estados Unidos", "Rusia", "Corea del Norte"],
  },
  {
    id: 7,
    title: "¿Cuál es la ciudad de los rascacielos?",
    answer: "New York",
    options: ["New York", "Londres", "Tokio", "Sidney"],
  },
  {
    id: 8,
    title: "¿En qué país se encuentra ubicada la Casa Rosada?",
    answer: "Argentina",
    options: ["Argentina", "Brasil", "Uruguay", "España"],
  },
  {
    id: 9,
    title: "¿Cuál es la capital de Nicaragua?",
    answer: "Managua",
    options: ["Managua", "San Jose", "Tegucigalpa", "La Paz"],
  },
  {
    id: 10,
    title: "¿En qué país está ubicada la ciudad de Medellín?",
    answer: "Colombia",
    options: ["Colombia", "Venezuela", "Perú", "Bolivia"],
  },
  {
    id: 11,
    title: "¿En qué continente se encuentra Surinam?",
    answer: "América de Sur",
    options: ["América de Sur", "Europa", "Asia", "África"],
  },
  {
    id: 12,
    title: "¿Cuál es la nación más pequeña del mundo?",
    answer: "El Vaticano",
    options: ["El Vaticano", "Chile", "Monaco", "Andorra"],
  },
  {
    id: 13,
    title: "¿Cuál es la única ciudad que está en dos continentes distintos?",
    answer: "Estambul",
    options: ["Estambul", "Berlin", "Moscu", "Londres"],
  },
  {
    id: 14,
    title: "¿Qué rama de la biología estudia a los animales?",
    answer: "Zoología",
    options: ["Zoología", "Botánica", "Fisiología", "Ecología"],
  },
  {
    id: 15,
    title: "¿Cuál es el animal más rápido del mundo?",
    answer: "Guepardo",
    options: ["Guepardo", "Condor", "Caballo", "Leopardo"],
  },
];
